version: "3"
services: 
    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    srv:
        build: ./srv/
        environment: 
            - PORT=3000

    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: myuser
            MONGO_INITDB_ROOT_PASSWORD: mypassword
        volumes: 
            - mongo-db:/data/db

    redis:
        image: redis
volumes: 
    mongo-db: