version: "3"
services:
    srv:
        build:
            context: ./srv/
            args:
                NODE_ENV: development
        volumes:
            - ./srv/:/app
            - /app/node_modules
        environment:
            - PORT=4000
            - NODE_ENV=development
            - MONGO_USER=myuser
            - MONGO_PASSWORD=mypassword
            - SESSION_SECRET=secret
        command: npm run dev
        depends_on: 
            - mongo
    mongo:
        environment:
            MONGO_INITDB_ROOT_USERNAME: myuser
            MONGO_INITDB_ROOT_PASSWORD: mypassword