version: "3"
services: 
    srv:
        build: ./srv/
        ports: 
            - "4000:4000"
        environment: 
            - PORT=4000

    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: myuser
            MONGO_INITDB_ROOT_PASSWORD: mypassword
        volumes: 
            - mongo-db:/data/db

    redis:
        image: redis
volumes: 
    mongo-db: