version: "3"
services: 
    products-service:
        build: ./products-service/
        ports: 
            - "4000:4000"
        environment: 
            - PORT=4000

    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: myuser
            MONGO_INITDB_ROOT_PASSWORD: mypassword
        volumes: 
            - mongo-db:/data/db
volumes: 
    mongo-db: