version: "3"
services:
    srv:
        build:
            context: ./srv/
            args:
                NODE_ENV: production
        environment: 
            - PORT=3001
            - NODE_ENV=development
        ports:
            - "3001:3001"
        command: npm start