version: "3"
services:
    nginx:
        ports:
            - "80:80"
    srv:
        build:
            context: ./srv/
            args:
                NODE_ENV: production
        environment: 
            - NODE_ENV=production
        command: npm start