version: "3"
services:
    nginx:
        ports:
            - "3000:80"
    srv:
        build:
            context: ./srv/
            args:
                NODE_ENV: development
        volumes:
            - ./srv/:/app:ro
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - MONGO_USER=myuser
            - MONGO_PASSWORD=mypassword
            - SESSION_SECRET=secret
        command: npm run dev
        depends_on: 
            - mongo
    mongo:
        environment:
            MONGO_INITDB_ROOT_USERNAME: myuser
            MONGO_INITDB_ROOT_PASSWORD: mypassword